version: "2.19.1"
services:
  web:
    container_name: resto_django
    build:
      context: ./restodjango/
    command: python manage.py runserver 0.0.0.0:8000
    #command: gunicorn base.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./restodjango/:/usr/src/app -static_files/:/usr/src/app/static_files
    depends_on:
      - postgre
      - redis
    expose:
      - 8000
    env_file:
      - ./.env/dev.env

  redis:
    container_name: resto_redis
    image: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

  postgre:
    container_name: resto_db
    image: postgre
    environment:
      - POSTGRE_DB = resto_db
      - POSTGRE_USER = admin
      - POSTGRES_PASSWORD = admin
    volumes:
      - resto_db/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles

volumes:
  static_files:
  resto_db:
  redis_volume_data:
