# Generated by Django 4.1.7 on 2023-05-30 03:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.CharField(editable=False, max_length=8)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('extension_name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('contact_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Contact number must start with + and include only digits.', regex='^(\\+[0-9]{1,12})|[0-9]{1,11}$')])),
                ('groups', models.ManyToManyField(blank=True, related_name='CustomerDetails', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='CustomerDetails', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=8)),
                ('name', models.CharField(default='', max_length=25)),
                ('picture', models.ImageField(default='', upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=8)),
                ('name', models.CharField(default='', max_length=25)),
                ('picture', models.ImageField(default='', upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sidedishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=8)),
                ('name', models.CharField(default='', max_length=25)),
                ('picture', models.ImageField(default='', upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(default=0)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets_with_first_name', to='jresto.customerdetails')),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets_with_last_name', to='jresto.customerdetails')),
                ('middle_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets_with_middle_name', to='jresto.customerdetails')),
            ],
        ),
    ]
