# Generated by Django 4.1.7 on 2023-08-09 07:14

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.CharField(editable=False, max_length=20)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('contact_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Contact number must start with + and include only digits.', regex='^(\\+[0-9]{1,12})|[0-9]{1,11}$')])),
                ('save_password', models.CharField(default='', max_length=20)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('user_level', models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer')], max_length=20)),
                ('date_updated', models.DateField(default=datetime.date.today)),
                ('groups', models.ManyToManyField(blank=True, related_name='CustomerDetails', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='CustomerDetails', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Contact number must start with + and include only digits.', regex='^(\\+[0-9]{1,12})|[0-9]{1,11}$')])),
                ('message', models.CharField(max_length=500)),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='drink__988161fa', max_length=16)),
                ('name', models.CharField(default='', max_length=25)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='food__20258938', max_length=16)),
                ('name', models.CharField(max_length=25)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='side__8b4b36a6', max_length=16)),
                ('name', models.CharField(default='', max_length=25)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cash', models.IntegerField(default=0)),
            ],
        ),
    ]
