# Generated by Django 4.1.7 on 2023-08-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='product_id',
            field=models.CharField(default='drink__3a618a59', max_length=16),
        ),
        migrations.AlterField(
            model_name='food',
            name='product_id',
            field=models.CharField(default='food__9ca10a8c', max_length=16),
        ),
        migrations.AlterField(
            model_name='side',
            name='product_id',
            field=models.CharField(default='side__332a7c24', max_length=16),
        ),
    ]
