# Generated by Django 4.1.7 on 2023-08-01 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Contact number must start with + and include only digits.', regex='^(\\+[0-9]{1,12})|[0-9]{1,11}$')])),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
