# Generated by Django 4.1.7 on 2023-08-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0002_alter_customadmin_uid_alter_customerdetails_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='drink',
            name='product_id',
            field=models.CharField(default='drink__63434b10', max_length=16),
        ),
        migrations.AlterField(
            model_name='food',
            name='product_id',
            field=models.CharField(default='food__9334c373', max_length=16),
        ),
        migrations.AlterField(
            model_name='side',
            name='product_id',
            field=models.CharField(default='side__bcdbe3ea', max_length=16),
        ),
    ]
