# Generated by Django 4.1.7 on 2023-08-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0002_alter_drink_product_id_alter_food_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='product_id',
            field=models.CharField(default='drink__28de1a84', max_length=16),
        ),
        migrations.AlterField(
            model_name='food',
            name='product_id',
            field=models.CharField(default='food__6361e8f1', max_length=16),
        ),
        migrations.AlterField(
            model_name='side',
            name='product_id',
            field=models.CharField(default='side__fb8a29dd', max_length=16),
        ),
    ]
