# Generated by Django 4.1.7 on 2023-08-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0003_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_bill',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
