# Generated by Django 4.1.7 on 2023-08-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0003_alter_customerdetails_gender_alter_drink_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='product_id',
            field=models.CharField(default='drink__04a5fef6', max_length=16),
        ),
        migrations.AlterField(
            model_name='food',
            name='product_id',
            field=models.CharField(default='food__29931d8c', max_length=16),
        ),
        migrations.AlterField(
            model_name='side',
            name='product_id',
            field=models.CharField(default='side__fb006574', max_length=16),
        ),
    ]
