# Generated by Django 4.1.7 on 2023-08-09 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0003_alter_drink_product_id_alter_food_product_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Contact number must start with + and include only digits.', regex='^(\\+[0-9]{1,12})|[0-9]{1,11}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='save_password',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='drink',
            name='product_id',
            field=models.CharField(default='drink__584a4d2b', max_length=16),
        ),
        migrations.AlterField(
            model_name='food',
            name='product_id',
            field=models.CharField(default='food__bb0672d5', max_length=16),
        ),
        migrations.AlterField(
            model_name='side',
            name='product_id',
            field=models.CharField(default='side__cd4d36b9', max_length=16),
        ),
    ]
