# Generated by Django 4.1.7 on 2023-05-30 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0003_alter_wallet_first_name_alter_wallet_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='wallet',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to='jresto.customerdetails'),
            preserve_default=False,
        ),
    ]
