# Generated by Django 4.1.7 on 2023-08-16 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0004_rename_wallet_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=16)),
                ('product_type', models.CharField(choices=[('Meal', 'Meal'), ('Drink', 'Drink'), ('Side', 'Side')], default='', max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Side',
        ),
    ]
