# Generated by Django 4.1.7 on 2023-08-01 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0004_remove_customerdetails_extension_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadmin',
            name='date_created',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AddField(
            model_name='customadmin',
            name='date_updated',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
