# Generated by Django 4.1.7 on 2023-05-30 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0005_customerdetails_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='date_updated',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='drink',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='drink',
            name='date_updated',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='date_updated',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='sidedish',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='sidedish',
            name='date_updated',
            field=models.DateField(default=''),
        ),
    ]
