# Generated by Django 4.1.7 on 2023-09-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0005_deliveryinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
