# Generated by Django 4.1.7 on 2023-08-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0005_customadmin_date_created_customadmin_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadmin',
            name='save_password',
            field=models.CharField(default='', max_length=25),
        ),
    ]
