# Generated by Django 4.1.7 on 2023-08-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0006_customadmin_save_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customadmin',
            name='middle_name',
        ),
    ]
