# Generated by Django 4.1.7 on 2023-09-21 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0007_deliveryinfo_date_created_alter_order_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_completed',
            field=models.DateField(auto_now=True, default=datetime.datetime(2023, 9, 21, 7, 20, 54, 163469, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_completed',
            field=models.DateField(auto_now=True, default=datetime.datetime(2023, 9, 21, 7, 21, 0, 188436, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
