# Generated by Django 4.1.7 on 2023-09-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0009_alter_order_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_completed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_completed',
            field=models.DateField(null=True),
        ),
    ]
