# Generated by Django 4.1.7 on 2023-09-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jresto', '0010_alter_order_date_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='', max_length=15),
        ),
    ]
